-- 코드를 입력하세요
SELECT F.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE * F.AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER AS F JOIN FOOD_PRODUCT AS P 
ON F.PRODUCT_ID = P.PRODUCT_ID 
WHERE F.PRODUCE_DATE LIKE "2022-05-%"
GROUP BY F.PRODUCT_ID
ORDER BY TOTAL_SALES DESC , F.PRODUCT_ID 

